### ISSUE TITLE
Consider using a cross-platform build system

### ISSUE THREAD

**Issue by sztomi** [jubatus/jubatus-msgpack-rpc#18]
The current build system heavily relies on a UNIX enviroment. While such environments are available for windows (mingw, cygwin), they are not really "native". It is impossible to compile with Visual Studio without constructing a project file by hand, which limits the portability of this library. CMake, Premake, SCons and others should be considered instead of shell scripts and makefiles.

**Comment by kumagi** [comment]
It is hard to build this project if this project used `cmake` or any other build system.
Because `jubatus-msgpack-rpc` depends on `jubatus-mpio` which hardly depends on `epoll` or `kqueue`.
Other solution like `libuv` or any other `epoll`/`kqueue` wrapper for windows is needed.

**Comment by starthal** [comment]
How difficult would it be to replace `mpio` with `libuv`? I am interested in porting this to Windows if it's possible.

**Comment by kmaehashi** [comment]
> How difficult would it be to replace mpio with libuv? I am interested in porting this to Windows if it's possible.
> EDIT: Or is it wavy that would need to be replaced with libuv?

Yes, you'll need to modify `wavy` layer of jubatus-mpio to bridge jubatus-mpio interface and underlying OS-dependent API.
I'm not sure how difficult it is; as both msgpack-rpc and mpio are originally not expected to be run on Windows, there may be some pitfalls.  Any follow-ups @kumagi?

**Comment by kumagi** [comment]
yes, `libuv` or others frameworks should replace wavy.
`libuv` doesn't support multi-threading, so there are some big jump needed between `wavy` and `libuv`.
