### ISSUE TITLE
'tuple_type' in namespace 'msgpack::v1::type' does not name a template type

### ISSUE THREAD

**Issue by timotheecour** [jubatus/jubatus-msgpack-rpc#25]
can't compile a program that uses:
# include <jubatus/msgpack/rpc/client.h>

```
In file included from /home/timothee/temp/stage3/usr/local/include/jubatus/msgpack/rpc/session.h:23:0,
from /home/timothee/temp/stage3/usr/local/include/jubatus/msgpack/rpc/client.h:23,
from /home/timothee/git_clone//lhrep//tests/test_msgpack_rpc.cpp:8:
/home/timothee/temp/stage3/usr/local/include/jubatus/msgpack/rpc/protocol.h:61:28: error:
'tuple_type' in namespace 'msgpack::v1::type' does not name a template type
typename msgpack::type::tuple_type<Parameter>::transparent_reference param,
```

see also https://github.com/jubatus/jubatus-msgpack-rpc/issues/24

is that related to https://github.com/jubatus/jubatus-msgpack-rpc/issues/21 ?

Is anyone using jubatus-msgpack-rpc ? Is this library still maintained? Not sure why I'm running into so many issues

**Comment by kmaehashi** [comment]
I could build a simple program using msgpack-c v1.4.2 + jubatus-msgpack-rpc (msgpack-1.x branch).

```cpp
#include <jubatus/msgpack/rpc/client.h>

int main() {
  msgpack::rpc::client c("localhost", 9199);
  msgpack::rpc::future f = c.call("test");
  f.get<bool>();
}
```

Please provide an example program to reproduce this issue.
