### ISSUE TITLE
configure is failing

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [jubatus/jubatus-msgpack-rpc#29]
```
./bootstrap
./configure
...
configure: error: Can't find msgpack library.
--with-msgpack=DIR option may be needed.
```

msgpack is a header only library and there no library for linking. Why is it looking for -lmsgpack ?

**Comment by aliawan01** [comment]
I've been having the same problem despite having installed msgpack-c. By running the following commands:
```
git clone https://github.com/msgpack/msgpack-c.git
cd msgpack-c
git checkout cpp_master
cmake .
sudo cmake --build . --target install
```

Which were supplied in installation section in the [readme](https://github.com/msgpack/msgpack-c/tree/cpp_master)
